core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("customuser.urls")),
]

customuser/urls.py
from django.urls import path, include

from . import views

app_name = "customuser"
urlpatterns = [
    path("", views.UserListView.as_view(), name="user_list"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("create-user/", views.UserCreateView.as_view(), name="create_user"),
    path("update-user/<int:id>/", views.UserUpdateView.as_view(), name="update_user"),
    path("logout/", views.log_out, name="logout"),
    path("login/", views.log_in, name="login"),
]

customuser/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from customuser.managers import CustomUserManager
from django.utils.translation import gettext as _
from .validators import validate_phone_number
from multiselectfield import MultiSelectField


class NewUser(AbstractUser):
    GENDER_CHOICES = (
        ("male", "Male"),
        ("female", "Female"),
    )
    username = None
    email = models.EmailField("email address", unique=True)
    first_name = models.CharField(_("First Name"), max_length=50)
    last_name = models.CharField(_("Last Name"), max_length=50)
    phone = models.CharField(
        _("Phone No."), max_length=10, unique=True, validators=[validate_phone_number]
    )
    dob = models.DateField(_("Date Of Birth"), blank=True, null=True)
    gender = models.CharField(
        _("Gender"), max_length=10, choices=GENDER_CHOICES, default=""
    )
    created_at = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "email"  # make the user log in with the email
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserInfo(models.Model):
    """
    User Info model to save user information.
    This is related with user table through OneToOne relation.
    """

    HOBBY_CHOICES = (
        ("sport", ("sport")),
        ("music", ("music")),
        ("travel", ("travel")),
        ("other", ("other")),
    )
    user = models.OneToOneField(
        NewUser,
        related_name="user_info",
        on_delete=models.CASCADE,
    )
    age = models.SmallIntegerField(default=0)
    hobbies = MultiSelectField(
        _("Hobbies"), max_length=50, choices=HOBBY_CHOICES, blank=True, null=True
    )

    def __str__(self):
        return f"{self.user.first_name}"

customuser/forms.py
from django import forms
from django.forms import widgets
from . import models


class NewUserForm(forms.ModelForm):
    class Meta:
        model = models.NewUser
        fields = ["first_name", "last_name", "email", "phone", "dob"]
        exclude = ["created_at"]
        widgets = {"dob": widgets.DateInput(attrs={"type": "date"})}

    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        self.fields["dob"].widget.attrs[
            "placeholder"
        ] = "Formate should be '(yyyy-mm-dd)'"


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ["hobbies", "age"]
        exclude = [
            "user",
        ]
        widgets = {"age": forms.HiddenInput()}


class LogInForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

customuser/views.py
from django.views.generic import View, ListView, DetailView
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect, render
from django.contrib import messages
from customuser.forms import LogInForm, UserInfoForm, NewUserForm
from .models import NewUser
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail
from .utils import get_age, get_gender_by_name, get_random_password
from django.contrib.auth import login, authenticate, logout


class UserListView(ListView):
    """
    A ListView to display all users
    """

    model = NewUser
    context_object_name = "user_list"
    template_name = "user_list.html"


class UserDetailView(DetailView):
    """
    A DetailView to display user detail
    """

    model = NewUser
    template_name = "user_detail.html"


class UserCreateView(View):
    """
    A UserCreateView to create user and userinfo.
    """

    template_name = "user_form.html"

    def get_success_url(self):
        return reverse("customuser:user_list")

    def get(self, request, *args, **kwargs):
        context = {
            "user_form": NewUserForm(),
            "user_info_form": UserInfoForm(),
        }
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        user_form = NewUserForm(request.POST)
        user_info_form = UserInfoForm(request.POST)
        if user_form.is_valid() and user_info_form.is_valid():
            user_form.cleaned_data["gender"] = get_gender_by_name(
                user_form.cleaned_data["first_name"]
            )
            random_password = get_random_password()
            user = NewUser.objects.create_user(
                password=random_password,
                **user_form.cleaned_data,
            )
            user.save()
            user_info = user_info_form.save(commit=False)
            user_info.user = user
            user_info.age = get_age(user.dob)
            user_info.save()
            send_mail(
                "User Created",
                f"Your user have been successfully created.\n\n Username : {user.email}\n\n Password : {random_password}",
                "from@admin.com",
                [user.email],
                fail_silently=False,
            )
            messages.success(request, "New user created.")
            return redirect(self.get_success_url())
        else:
            context = {
                "user_form": user_form,
                "user_info_form": user_info_form,
            }
            return render(request, self.template_name, context=context)


class UserUpdateView(View):
    """
    A UserUpdateView to update user and userinfo.
    """

    template_name = "user_form.html"

    def get_success_url(self):
        return reverse("customuser:user_list")

    def get(self, request, id, *args, **kwargs):
        user = get_object_or_404(NewUser, pk=id)
        context = {
            "user_form": NewUserForm(instance=user),
            "user_info_form": UserInfoForm(instance=user.user_info),
        }
        return render(request, self.template_name, context=context)

    def post(self, request, id, *args, **kwargs):
        user = get_object_or_404(NewUser, pk=id)
        user_form = NewUserForm(request.POST, instance=user)
        user_info_form = UserInfoForm(request.POST, instance=user.user_info)
        if user_form.is_valid() and user_info_form.is_valid():
            user_form.save()
            user_info_form.save()
            messages.success(request, "User details updated.")
            return redirect(self.get_success_url())
        else:
            context = {
                "user_form": user_form,
                "user_info_form": user_info_form,
            }
            return render(request, self.template_name, context=context)


def log_out(request):
    logout(request)
    messages.success(request, "Logged out.")
    return redirect(reverse("customuser:user_list"))


def log_in(request):
    if request.user.is_authenticated:
        return redirect("customuser:user_list")
    if request.method == "POST":
        form = LogInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                messages.success(request, "Logged in.")
                return redirect("customuser:user_list")
    else:
        form = LogInForm()
    return render(request, "login.html", {"form": form})

customuser/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
        <script src="https://use.fontawesome.com/8707e32926.js"></script>
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            <nav class="row" style="background: black; color: white;">
              <h1 class="col-md-12 text-center">User CRUD</h1>
            </nav>
            <div class="d-flex justify-content-end align-items-center pt-2">
              {% if user.is_authenticated %}
                <a href="#" class="nav-link mx-2">{{ user.get_username }}</a>
                <a href="{% url 'customuser:logout' %}" class="btn btn-primary">Logout</a>
              {% else %}
                <a href="{% url 'customuser:login' %}" class="btn btn-primary">Login</a>
              {% endif %}
            </div>
            {% if messages %}
              <div class="container pt-2">
                {% for message in messages %}
                  <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message  }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
            {% block body %}
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>

customuser/templates/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container m-5 p-5 mt-0">
    {% if form.errors%}
    {% for field in form %}
    {% if field.errors %}
    <div class="alert alert-danger" role="alert">
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" class="btn btn-primary mb-3">
    </form>
</div>
{% endblock%}

customuser/templates/user_detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container m-5 p-5 pt-0">
    <div class="row">
        <div class="col-8">
            <h2 class="pb-4">User Detail</h2>    
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-success" href="{% url 'customuser:user_list' %}" role="button"><i class="fa fa-list-ol" aria-hidden="true"></i> User List</a>
            <div class="p-3">
                <a class="btn btn-warning" href="{% url 'customuser:update_user' object.id %}" role="button"><i class="fa fa-pencil" aria-hidden="true"></i> Update User</a>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>First Name</b>
            </div>
            <div class="col">
                {{object.first_name}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Last Name</b>
            </div>
            <div class="col">
                {{object.last_name}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Gender</b>
            </div>
            <div class="col">
                {{object.gender}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Username</b>
            </div>
            <div class="col">
                {{object.email}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Phone Number</b>
            </div>
            <div class="col">
                {{object.phone}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Date Of Birth</b>
            </div>
            <div class="col">
                {{object.dob}}
            </div>
        </div>
        <hr />
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Age</b>
            </div>
            <div class="col">
                {{object.user_info.age}}
            </div>
        </div>
        <div class="row align-items-start mt-3">
            <div class="col-4">
                <b>Hobbies</b>
            </div>
            <div class="col">
                {{object.user_info.hobbies}}
            </div>
        </div>
    </div>
</div>
{% endblock %}

customuser/templates/user_form.html
{% extends 'base.html' %}
{% block body %}
<div class="container m-5 p-5 mt-0">
    <div class="row">
        <div class="col-8">
            <h2 class="pb-4">{% if user_form.instance.pk %} Update User {% else %} Create User {% endif %}</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-success" href="{% url 'customuser:user_list' %}" role="button"> <i class="fa fa-list-ol" aria-hidden="true"></i> User List</a>
        </div>
    </div>
    {% if user_form.errors%}
    {% for field in user_form %}
    {% if field.errors %}
    <div class="alert alert-danger" role="alert">
        {{ field.errors|striptags }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    {% if user_address_form.errors%}
    {% for field in user_address_form %}
    {% if field.errors %}
    <div class="alert alert-danger" role="alert">
        {{field.name}} : {{ field.errors|striptags }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{user_form.as_p}}
        {{user_info_form.as_p}}
        <input type="submit" value="Submit" class="btn btn-primary mb-3">
    </form>
</div>
{% endblock%}

customuser/templates/user_list.html
{% extends 'base.html' %}

{% block body %}
<div class="container m-5 p-5 pt-0">
    <div class="row">
        <div class="col-8">
            <h2>Users List</h2>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="btn btn-primary" href="{% url 'customuser:create_user' %}" role="button"><i class="fa fa-plus" aria-hidden="true"></i> Create User</a>
        </div>
    </div>
    <table class="table mt-4">
        <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Username</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{user.first_name}}</td>
                <td>{{user.last_name}}</td>
                <td>{{user.email}}</td>
                <td>
                    <a class="btn btn-warning" href="{% url 'customuser:update_user' user.id %}" role="button"><i class="fa fa-pencil" aria-hidden="true"></i> Update</a>
                    <a class="btn btn-info" href='{% url "customuser:user_detail" user.id %}'> <i class="fa fa-eye" aria-hidden="true"></i> View </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}